# Generated by Django 5.0 on 2025-12-09 06:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(help_text="Emoji or icon name", max_length=50),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template Category",
                "verbose_name_plural": "Template Categories",
                "db_table": "template_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[("free", "Free"), ("pro", "Pro")],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("sessions_used_this_month", models.IntegerField(default=0)),
                (
                    "sessions_reset_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "user_prompt_display",
                    models.TextField(
                        help_text="What user sees: 'Write an email about {topic}'"
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        help_text="Full prompt with {{ variable }} placeholders (Jinja2/Django template syntax)"
                    ),
                ),
                (
                    "variables_schema",
                    models.JSONField(
                        default=list,
                        help_text="JSON schema defining variables structure",
                    ),
                ),
                (
                    "estimated_tokens",
                    models.IntegerField(
                        default=100, help_text="Estimated output token count"
                    ),
                ),
                (
                    "best_for",
                    models.JSONField(
                        default=list,
                        help_text="List of AI models this works best with (e.g., ['ChatGPT', 'Claude'])",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="Tags for search and filtering"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="core.templatecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt Template",
                "verbose_name_plural": "Prompt Templates",
                "db_table": "prompt_templates",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="WhisperSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("variables_collecting", "Collecting Variables"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                (
                    "variables_input",
                    models.JSONField(
                        default=dict, help_text="Raw voice transcriptions per variable"
                    ),
                ),
                (
                    "variables_processed",
                    models.JSONField(
                        default=dict,
                        help_text="Processed/transformed variables ready for template",
                    ),
                ),
                ("generated_prompt", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="core.prompttemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Whisper Session",
                "verbose_name_plural": "Whisper Sessions",
                "db_table": "whisper_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceInput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("variable_name", models.CharField(max_length=100)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="voice_inputs/%Y/%m/%d/"
                    ),
                ),
                ("audio_duration_ms", models.IntegerField(default=0)),
                (
                    "transcription_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transcribed_text", models.TextField(blank=True)),
                ("transcription_confidence", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_inputs",
                        to="core.whispersession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Input",
                "verbose_name_plural": "Voice Inputs",
                "db_table": "voice_inputs",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_name", models.CharField(max_length=200)),
                ("template_category", models.CharField(max_length=100)),
                (
                    "prompt_preview",
                    models.CharField(
                        help_text="First 200 chars for list display", max_length=200
                    ),
                ),
                ("full_prompt", models.TextField()),
                ("variables_used", models.JSONField(default=dict)),
                ("is_favorite", models.BooleanField(default=False)),
                ("copy_count", models.IntegerField(default=0)),
                ("last_copied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entry",
                        to="core.whispersession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt History",
                "verbose_name_plural": "Prompt History",
                "db_table": "prompt_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(fields=["slug"], name="prompt_temp_slug_f766f2_idx"),
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(
                fields=["category", "is_active"], name="prompt_temp_categor_a8b087_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(
                fields=["-usage_count"], name="prompt_temp_usage_c_a2aba3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whispersession",
            index=models.Index(
                fields=["user", "-created_at"], name="whisper_ses_user_id_27c5c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whispersession",
            index=models.Index(fields=["status"], name="whisper_ses_status_5181bc_idx"),
        ),
        migrations.AddIndex(
            model_name="voiceinput",
            index=models.Index(
                fields=["session", "variable_name"],
                name="voice_input_session_c8c254_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voiceinput",
            index=models.Index(
                fields=["transcription_status"], name="voice_input_transcr_66a942_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompthistory",
            index=models.Index(
                fields=["user", "-created_at"], name="prompt_hist_user_id_899ee0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompthistory",
            index=models.Index(
                fields=["user", "is_favorite"], name="prompt_hist_user_id_7c21cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompthistory",
            index=models.Index(
                fields=["-created_at"], name="prompt_hist_created_019038_idx"
            ),
        ),
    ]
